name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: kivy/buildozer
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build APK
      run: |
        buildozer android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: myapp-apk
        path: bin/*.apk
